### PR TITLE
add first dockerfile

### PR DESCRIPTION
**Pull request by nuest**
A first working version of the Dockerfile. Missing:

- [x] retrieve the model output from the container and visualize it
- [x] instructions in README how to use the Dockerfile
- [x] deploy image to Docker Hub

### CODE REVIEW

**Comment by nuest** [comment]
@JudithVerstegen Is there any nice command that creates png preview/rendering of the output maps, which a user could open without having aguila on the host machine?

**Comment by JudithVerstegen** [comment]
> @JudithVerstegen Is there any nice command that creates png preview/rendering of the output maps, which a user could open without having aguila on the host machine?

@nuest I added code to automatically create movies (mp4 files) of the output maps. The first movie is land use change for a single Monte Carlo sample and matches Figure 2 in the article (http://www.sciencedirect.com/science/article/pii/S0198971511000883#f0010). The second movie is the availability of land for eucalyptus and matches Figure 5 in the article (http://www.sciencedirect.com/science/article/pii/S0198971511000883#f0025). This one is only created when the model is run stochastically, i.e. with more than one Monte Carlo sample. 

For this you need to install ffmpeg and the matplotlib python library. Does this help?

**Comment by nuest** [comment]
Yes, that would surely help. I assume the changes are in https://github.com/JudithVerstegen/PLUC_Mozambique/commit/96553774c9ed0ac50a4b6580307ba09efae0477c - I will update the Dockerfile soon and try out the video rendering. _Thanks!_

**Comment by JudithVerstegen** [comment]
> Yes, that would surely help. I assume the changes are in 9655377 - I will update the Dockerfile soon and try out the video rendering. Thanks!

Yes, these are the changes I am referring to. Looking forward to your update, thanks!

**Comment by nuest** [comment]
The videos are created. Can you please check if they look as expected?

https://uni-muenster.sciebo.de/index.php/s/QMR5EwQsh0EdWZD

**Comment by JudithVerstegen** [comment]
The maps themselves look as expected but the legends not. The bar should
not be double and the other one should not overlap the map. What matplotlib
version did you use?

**Comment by nuest** [comment]
Yes, I suspected those were not as they should be.

The version of matplotlib is `2.0.2`.

Potentially the issue lies in the fact that I needed to user `backend: Agg`, because in the container there is no display. That might result in different rendering. See  https://stackoverflow.com/questions/2801882/generating-a-png-with-matplotlib-when-display-is-undefined

(Note to self: Got the version via `root@12d1c3ba93d6:/pluc# python -c "import matplotlib; print matplotlib.__version__"`)

**Comment by JudithVerstegen** [comment]
Thanks for the suggestions. I was able to reproduce and solve the problem
with the double legend in movie_euSc-ave.mp4. This behaviour was indeed
because of the backend Agg. It was solved when I turned off 'blitting' (
http://matplotlib.org/api/animation_api.html#funcanimation).

By the way, I now integrated the backend Agg in the scripts, so you do not
have to put it in the Docker file anymore (I hope).

I could not reproduce the problem of the legend overlapping the map in
movie_landUse.mp4. I now plot the legend relative to the whole figure
instead of relative to the map (axis) and I have created a bit more space
between legend and map. I hope this will make the result better. And, just
to be sure, I also turned off blitting for this movie.

2017-07-10 9:16 GMT+02:00 Daniel Nüst <notifications@github.com>:

**Comment by nuest** [comment]
The image is on Docker Hub now, but based on my fork of this repo (which is fine for now I would say): https://hub.docker.com/r/nuest/pluc_mozambique/

Some metadata can easily be explored here: https://microbadger.com/images/nuest/pluc_mozambique

@JudithVerstegen I can show you offline how Docker Hub works if you think that is useful to you.

So what is left is documentation, I'll notify here when it's ready.

**Comment by nuest** [comment]
The image is on Docker Hub now, but based on my fork of this repo (which is fine for now I would say): https://hub.docker.com/r/nuest/pluc_mozambique/

Some metadata can easily be explored here: https://microbadger.com/images/nuest/pluc_mozambique

@JudithVerstegen I can show you offline how Docker Hub works if you think that is useful to you.

So what is left is documentation, I'll notify here when it's ready.

**Comment by nuest** [comment]
@JudithVerstegen added the docs - done from my side, looking forward to your feedback.

I took the liberty to also use Markdown syntax supported by GitHub so the README is rendered more nicely, see https://github.com/nuest/PLUC_Mozambique/blob/master/README.md

**Comment by nuest** [comment]
@JudithVerstegen ready to be merged from my side.

**Pull request merged**
